### ISSUE TITLE
AWS credentials

### ISSUE THREAD

**Issue by yurinnick** [pandastrike/rephraser#10]
Hi!
I've investigated some security issues on public repos and found that you have open AWS creds [here](https://github.com/pandastrike/rephraser/blob/c4bd1b6d430b0466f03d8d8f01bb167addf9bce3/ansible/roles/elasticsearch/vars/main.yml). I didn't do any harm and didn't took any data. I suggest you to remove your AWS creds from public ASAP and regenerate it on your AWS dashboard.

**Comment by automatthew** [comment]
Thank you for this report.
